server:
  port: 18006 #指定运行端口
logging:
  level:
    root: INFO
  file:
    name: logs/${spring.application.name}.log
    path: logs
spring:
  application:
    name: spring-admin #指定服务名称
  thymeleaf:
    enabled: true
    cache: true
    encoding: UTF-8
    prefix: classpath:/templates/
    check-template-location: true
    mode: HTML
    suffix: .html
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
