server:
  port: 8080 #指定运行端口
logging:
  level:
    root: INFO
  file:
    name: logs/${spring.cloud.client.ip-address}/${spring.application.name}.log
    path: logs
spring:
  application:
      name: config-server #指定服务名称
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  thymeleaf:
    enabled: true
    cache: true
    encoding: UTF-8
    prefix: classpath:/templates/
    check-template-location: true
    mode: HTML
    suffix: .html
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address} #指定主机地址
    instance-id:  ${spring.cloud.client.ip-address} :${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://wengjp:wengjp123@wengjp.local:9001/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always